### input
mesh: 
prompt: 
seed: "random"
### mesh's front-facing direction, check mesh.py for details
front_dir: "+z"

### output
outdir: logs
save_path: out.obj

### SD 1.5 checkpoint
model_key: xiaolxl/GuoFeng3
# lora_keys: [civitai_weights/MoXinV1.safetensors]
lora_keys: []

### additional positive/negative prompt
posi_prompt: "best quality, masterpiece, highres, china dress, Beautiful face"
nega_prompt: "NSFW, lowres,bad anatomy,bad hands, text, error, missing fingers,extra digit, fewer digits, cropped, worstquality, low quality, normal quality,jpegartifacts,signature, watermark, username,blurry,bad feet"

### controlnet model
control_mode: ['depth_inpaint']

### whether append 'front/side/back/top/bottom view' for the prompt, only use if the mesh's front dir is correctly set.
text_dir: true

### camera path to generate the texture
camera_path: front

### background image, default to white.
bg_image: None # assets/brick_wall.png

### generated texture image resolution
texture_size: 1024

### camera rendering resolution (choose from [512, 1024, 2048, 4096], larger than 512 will incur Real-ESRGAN super-resolution)
render_resolution: 1024

### threshold for view cosine value
cos_thresh: 0

### refine strength (larger value means less strong refinement)
refine_strength: 0.6

### open a gui for visualization (need a screen)
gui: false

### visualize intermediate results (support x11 forwarding)
vis: false

### recalculate uv coordinate for mesh
retex: false
remesh: false

### gui resolution
H: 800
W: 800

### camera setting
radius: 2.5
fovy: 50